package com.page.ling.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACTS".
 */
public class contacts {

    private Long id;
    private String phoneNum;
    /** Not-null value. */
    private String phoneName;
    private Boolean switchFlag;
    private byte[] phonePhoto;
    private java.util.Date date;

    public contacts() {
    }

    public contacts(Long id) {
        this.id = id;
    }

    public contacts(Long id, String phoneNum, String phoneName, Boolean switchFlag, byte[] phonePhoto, java.util.Date date) {
        this.id = id;
        this.phoneNum = phoneNum;
        this.phoneName = phoneName;
        this.switchFlag = switchFlag;
        this.phonePhoto = phonePhoto;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /** Not-null value. */
    public String getPhoneName() {
        return phoneName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoneName(String phoneName) {
        this.phoneName = phoneName;
    }

    public Boolean getSwitchFlag() {
        return switchFlag;
    }

    public void setSwitchFlag(Boolean switchFlag) {
        this.switchFlag = switchFlag;
    }

    public byte[] getPhonePhoto() {
        return phonePhoto;
    }

    public void setPhonePhoto(byte[] phonePhoto) {
        this.phonePhoto = phonePhoto;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
