package com.page.ling.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.page.ling.greendao.contacts;

import com.page.ling.greendao.contactsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsDaoConfig;

    private final contactsDao contactsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsDaoConfig = daoConfigMap.get(contactsDao.class).clone();
        contactsDaoConfig.initIdentityScope(type);

        contactsDao = new contactsDao(contactsDaoConfig, this);

        registerDao(contacts.class, contactsDao);
    }
    
    public void clear() {
        contactsDaoConfig.getIdentityScope().clear();
    }

    public contactsDao getContactsDao() {
        return contactsDao;
    }

}
